version: "3"

services:
  faktory:
    image: contribsys/faktory:latest
    ports:
      - 7419:7419
      - 7420:7420
    environment:
      - FAKTORY_PASSWORD=aErlnoRkA3r5v0D
    command: /faktory -b :7419 -w :7420 -e production

  redis:
    image: "redis:alpine"

  api-server:
    image: $API_IMAGE
    restart: always
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443

  example-worker:
    image: $WORKER_IMAGE
    restart: always
    env_file:
      - .env
    command: python run_worker.py -w example

